[package]
name = "rustfft_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustfft_test"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.16.1"
num-complex = "0.4.6"
numpy = "0.21.0"
pyo3 = "0.21.0"
rustfft = { git="https://github.com/ejmahler/RustFFT.git", branch = "master" }
